### ISSUE TITLE
[CHECKLIST] VAnchor wasm-utils integration into sdk-core

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb.js#193]
## Overview

Task related to vanchor integration into webb.js. 

- [x] Note generation tests in Typescript
- [ ] Proof generation tests in Typescript
- [x] Add a vanchor option to the note
- [x] Tests of serializing and deserializing between VAnchor Notes / UTXOs

**Comment by dutterbutter** [comment]
Closing in favour of #106
