### ISSUE TITLE
[TASK] Update all dependencies and upgrade node to v18.14 LTS

### ISSUE THREAD

**Issue by salman01zp** [webb-tools/webb.js#312]
## Task Checklist

 - [x] Upgrade node engine to v18.x.x
 - [x] Upgrade all dependencies to latest
 - [x] Upgrade webpack to support node v18
 - [x] Update CI to use node v18.x.x
 - [x] Fix substrate tests
